#https://medium.com/codex/understanding-djangos-apps-and-appconfig-2cb57e44c80e

##django project is collection of apps
##the application server loads all apps and genertes AppConfig for each apps and stores in apps class
from django.apps import AppConfig

class MyAppConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'my_app'



##The __pycache__ folder is a directory automatically generated by Python to store compiled bytecode files (.pyc) when Python modules are imported or executed. 
##Python compiles the source code (.py) into bytecode (.pyc) before execution. The bytecode is then executed by the Python interpreter. 